- hosts: all 
  gather_facts: false
  become: true

  roles:
   - baseconfig

- hosts: frontends
  gather_facts: false
  become: true
  roles:
   - haproxy
- hosts: apps
  gather_facts: false
  become: true
  roles:
   - tomcat
